url: "https://sdslab.uk"
baseurl: ""  # Must be EMPTY because the domain is now pointing directly to this project root

title: "UCL's Safer Digital Services Lab"
description: "Creating safer online digital services through research."
url: ""

collections:
  people:
    output: false
  previous_people:
    output: false
  research:
    output: true
  news:
    output: true
  themes:
    output: false